import type { WorkflowDefinition } from "../types";

export const CHURCH_DOC_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "church.creative_brief_to_production",
    title: "Creative brief → production",
    vertical: "church",
    summary:
      "Alignment first: creative brief locks audience, tone, and deliverables — then routes to the right production workflow.",
    whenToUse: [
      "Any campaign, series, event promo, or brand work before templates open",
      "Cross-team creative request intake",
    ],
    whenNotToUse: ["Emergency/crisis comms — use approval fast-track", "Repeat weekly sermon batch with existing series kit"],
    estimatedMinutes: 45,
    primaryPlatforms: ["Internal", "Canva/Figma", "Social"],
    skillsUsed: [
      "church.doc-architecture.write_creative_brief",
      "church.ops.intake_creative_brief_form",
      "church.ops.duplicate_template_not_redesign",
    ],
    docPath: "church/workflows/creative-brief-to-production.md",
    steps: [
      {
        id: "intake",
        title: "Intake request",
        description: "Who is asking, what they need, by when, and which campus/ministry.",
        type: "input",
        inputs: [
          { key: "requester", label: "Requester / ministry", required: true },
          { key: "due_date", label: "Due date", required: true },
          { key: "request_summary", label: "What do you need?", required: true, multiline: true },
        ],
      },
      {
        id: "creative_brief",
        title: "Write creative brief",
        description: "Audience, objective, tone, deliverables, constraints — alignment only, not approval.",
        type: "skill",
        skillId: "church.doc-architecture.write_creative_brief",
      },
      {
        id: "route",
        title: "Route to production workflow",
        description: "Pick downstream workflow based on deliverable type.",
        type: "checklist",
        checklistItems: [
          "Sermon/social batch → sermon-to-social",
          "Sunday kit → weekly-service-kit",
          "New series → series-launch",
          "Event / special production → big-day-charter first if large scope",
        ],
      },
      {
        id: "align",
        title: "Comms lead alignment sign-off",
        description: "Confirm brief is clear — not final creative approval.",
        type: "gate",
        gateCriteria: ["Audience defined", "Deliverables listed", "Brand/series kit referenced", "Timeline realistic"],
      },
    ],
    outputChecklist: ["Creative brief PDF/Doc", "Routed workflow name", "DAM folder path"],
    relatedWorkflows: ["church.sermon_to_social", "church.weekly_service_kit"],
  },
  {
    id: "church.big_day_charter",
    title: "Big day project charter",
    vertical: "church",
    summary:
      "Authorize major Sundays, events, and productions with sponsor, scope, RACI, risk register, and success criteria.",
    whenToUse: [
      "Easter, Christmas, conference, baptism Sunday, major guest",
      "Multi-team production with budget or vendor impact",
    ],
    whenNotToUse: ["Standard weekly service kit", "Single social graphic"],
    estimatedMinutes: 120,
    primaryPlatforms: ["Internal", "ProPresenter", "Events"],
    skillsUsed: [
      "church.doc-architecture.write_project_charter",
      "church.doc-architecture.write_raci_matrix",
      "church.doc-architecture.write_risk_register",
      "church.doc-architecture.write_run_of_show",
    ],
    docPath: "church/workflows/big-day-charter.md",
    steps: [
      {
        id: "concept",
        title: "Concept note (optional)",
        description: "If idea is still early, capture concept note before full charter.",
        type: "skill",
        skillId: "church.doc-architecture.write_concept_note",
        optional: true,
      },
      {
        id: "charter",
        title: "Project charter",
        type: "input",
        inputs: [
          { key: "event_name", label: "Event / big day name", required: true },
          { key: "event_date", label: "Date", required: true },
          { key: "executive_sponsor", label: "Executive sponsor", required: true },
          { key: "success_criteria", label: "Success criteria", required: true, multiline: true },
          { key: "out_of_scope", label: "Explicitly out of scope", required: true, multiline: true },
        ],
      },
      {
        id: "raci",
        title: "RACI matrix",
        type: "skill",
        skillId: "church.doc-architecture.write_raci_matrix",
      },
      {
        id: "risk",
        title: "Risk register",
        description: "Production, safety, comms, volunteer, weather — mitigation owners assigned.",
        type: "skill",
        skillId: "church.doc-architecture.write_risk_register",
      },
      {
        id: "ros",
        title: "Run of show draft",
        type: "skill",
        skillId: "church.doc-architecture.write_run_of_show",
      },
      {
        id: "approve",
        title: "Leadership authorization",
        type: "gate",
        gateCriteria: ["Executive sponsor signed", "Budget boundary clear", "RACI published to teams"],
      },
    ],
    outputChecklist: ["Project charter", "RACI", "Risk register", "ROS v1", "Approval recorded"],
    relatedWorkflows: ["church.weekly_service_kit", "church.post_event_aar"],
  },
  {
    id: "church.post_event_aar",
    title: "After action report (post-event)",
    vertical: "church",
    summary: "Within 72 hours of event: what worked, what didn't, owners for improvements — feeds next charter.",
    whenToUse: ["After any big day, series launch weekend, or major event"],
    whenNotToUse: ["Before event completes"],
    estimatedMinutes: 60,
    primaryPlatforms: ["Internal", "Leadership"],
    skillsUsed: ["church.doc-architecture.write_after_action_report", "church.doc-architecture.write_decision_memo"],
    docPath: "church/workflows/post-event-aar.md",
    steps: [
      {
        id: "event_ref",
        title: "Event reference",
        type: "input",
        inputs: [
          { key: "event_name", label: "Event name", required: true },
          { key: "event_date", label: "Event date", required: true },
          { key: "charter_link", label: "Link to project charter (if any)", required: false },
        ],
      },
      {
        id: "gather",
        title: "Gather input",
        description: "Comms, worship, production, volunteers — 15 min each, async OK.",
        type: "checklist",
        checklistItems: [
          "Comms debrief",
          "Production debrief",
          "Worship debrief",
          "Volunteer lead debrief",
        ],
      },
      {
        id: "aar",
        title: "Write AAR",
        type: "skill",
        skillId: "church.doc-architecture.write_after_action_report",
      },
      {
        id: "decisions",
        title: "Decision records",
        description: "Any policy or process changes → decision memo, not Slack-only.",
        type: "skill",
        skillId: "church.doc-architecture.write_decision_memo",
        optional: true,
      },
      {
        id: "scorecard",
        title: "Update scorecard",
        description: "Lag indicators: attendance, engagement, volunteer fill, social reach.",
        type: "skill",
        skillId: "church.doc-architecture.write_scorecard",
        optional: true,
      },
      {
        id: "gate",
        title: "Experience Division lead review",
        type: "gate",
        gateCriteria: ["Improvements have owners and dates", "Charter folder updated", "Shared with leadership"],
      },
    ],
    outputChecklist: ["AAR document", "Decision memos if needed", "Scorecard updated", "Lessons linked to next charter"],
    relatedWorkflows: ["church.big_day_charter"],
  },
];
