import type { WorkflowDefinition } from "../types";

export const CORPORATE_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "corporate-marketing.thought_leadership",
    title: "Executive thought leadership program",
    vertical: "corporate-marketing",
    summary: "Turn one executive insight into LinkedIn posts, byline outline, and visual system for a quarter.",
    whenToUse: [
      "CEO/CMO wants consistent LinkedIn presence",
      "Building employer brand through leadership voice",
    ],
    whenNotToUse: ["Product launch week (use PMM workflow)", "Crisis comms"],
    estimatedMinutes: 120,
    primaryPlatforms: ["LinkedIn", "Company blog", "Email"],
    skillsUsed: [
      "corporate-marketing.content.executive_thought_leadership_program",
      "corporate-marketing.digital.linkedin_company_page_system",
      "marketing-stack.ai.route_tool_for_job",
    ],
    docPath: "corporate-marketing/workflows/thought-leadership.md",
    steps: [
      {
        id: "positioning",
        title: "Executive positioning",
        description: "Define the 3 themes this exec owns for 90 days.",
        type: "input",
        inputs: [
          { key: "exec_name", label: "Executive name & title", required: true },
          { key: "themes", label: "3 thought leadership themes", required: true, multiline: true },
          { key: "proof_points", label: "Proof points (metrics, wins)", required: true, multiline: true },
        ],
      },
      {
        id: "stakeholder_matrix",
        title: "Stakeholder messaging",
        description: "Align exec voice with investor, customer, and talent audiences.",
        type: "skill",
        skillId: "corporate-marketing.strategy.map_stakeholder_messaging_matrix",
      },
      {
        id: "platform",
        title: "Channel selection",
        type: "route",
        routeObjective: "b2b_pipeline",
        description: "LinkedIn primary; email and events secondary.",
      },
      {
        id: "content_calendar",
        title: "12-week post calendar",
        description: "2 posts/week: 1 story, 1 insight. No product pitches >20% of posts.",
        type: "skill",
        skillId: "corporate-marketing.content.executive_thought_leadership_program",
      },
      {
        id: "linkedin_visuals",
        title: "LinkedIn visual system",
        description: "Banner, quote cards, carousel template — real headshot for profile hero only.",
        type: "generate",
        jobType: "corporate_hero",
        promptTemplate: "Professional LinkedIn thought leadership graphic, minimal, {{brand_colors}}, no AI faces",
      },
      {
        id: "byline_outline",
        title: "Byline / long-form outline",
        description: "One HBR-style essay outline per month from best-performing posts.",
        type: "skill",
        skillId: "editorial-marketing.writing.executive_byline_ghostwriting",
        optional: true,
      },
      {
        id: "gate",
        title: "Exec approval",
        type: "gate",
        gateCriteria: ["Exec reviewed voice", "Legal cleared claims", "No confidential data"],
      },
    ],
    outputChecklist: [
      "12-week calendar",
      "LinkedIn banner + 3 template variants",
      "4 byline outlines",
      "Approval log",
    ],
    relatedWorkflows: ["corporate-marketing.case_study", "editorial-marketing.pillar_page"],
  },
  {
    id: "corporate-marketing.case_study",
    title: "Customer case study production",
    vertical: "corporate-marketing",
    summary: "Interview → PDF → web page → social cutdown — full customer story pipeline.",
    whenToUse: ["New enterprise win to promote", "Sales needs proof for a vertical"],
    whenNotToUse: ["Customer has not agreed to public reference"],
    estimatedMinutes: 180,
    primaryPlatforms: ["Web", "LinkedIn", "Sales deck"],
    skillsUsed: [
      "corporate-marketing.sales.case_study_production_workflow",
      "corporate-marketing.sales.sales_enablement_deck_system",
    ],
    docPath: "corporate-marketing/workflows/case-study-production.md",
    steps: [
      {
        id: "intake",
        title: "Customer intake",
        type: "input",
        inputs: [
          { key: "customer_name", label: "Customer name", required: true },
          { key: "industry", label: "Industry", required: true },
          { key: "challenge", label: "Challenge (before)", required: true, multiline: true },
          { key: "solution", label: "Solution", required: true, multiline: true },
          { key: "results", label: "Quantified results", required: true, multiline: true },
        ],
      },
      {
        id: "interview",
        title: "Interview guide",
        type: "skill",
        skillId: "corporate-marketing.sales.case_study_production_workflow",
      },
      {
        id: "pdf",
        title: "PDF one-pager",
        description: "Sales-ready PDF with logo, quote, metrics callout.",
        type: "generate",
        jobType: "corporate_hero",
        promptTemplate: "Enterprise case study hero, abstract professional, {{industry}} context, no stock faces",
      },
      {
        id: "web",
        title: "Web case study page",
        type: "skill",
        skillId: "corporate-marketing.digital.corporate_website_information_architecture",
      },
      {
        id: "social",
        title: "LinkedIn cutdown",
        type: "generate",
        jobType: "campaign_photo",
        promptTemplate: "LinkedIn case study announcement graphic, metric-forward, on-brand",
      },
      {
        id: "sales_deck",
        title: "Add to sales deck",
        type: "skill",
        skillId: "corporate-marketing.sales.sales_enablement_deck_system",
      },
      {
        id: "gate",
        title: "Customer sign-off",
        type: "gate",
        gateCriteria: ["Customer approved quote", "Legal approved", "Metrics verified"],
      },
    ],
    outputChecklist: ["PDF", "Web URL", "LinkedIn post", "Sales deck slide"],
    relatedWorkflows: ["corporate-marketing.sales_enablement_sprint"],
  },
  {
    id: "corporate-marketing.sales_enablement_sprint",
    title: "Sales enablement sprint",
    vertical: "corporate-marketing",
    summary: "One week to refresh battlecards, deck modules, and objection one-pagers for a segment.",
    whenToUse: ["New vertical push", "Competitive landscape shifted"],
    whenNotToUse: ["Full rebrand in progress"],
    estimatedMinutes: 240,
    primaryPlatforms: ["Sales deck", "CRM attachments", "Internal wiki"],
    skillsUsed: [
      "corporate-marketing.sales.sales_enablement_deck_system",
      "product-marketing.strategy.competitive_battlecard_system",
    ],
    docPath: "corporate-marketing/workflows/sales-enablement-sprint.md",
    steps: [
      {
        id: "segment",
        title: "Define segment",
        type: "input",
        inputs: [
          { key: "segment", label: "Target segment", required: true },
          { key: "competitors", label: "Top 3 competitors", required: true },
        ],
      },
      {
        id: "battlecards",
        title: "Battlecards",
        type: "skill",
        skillId: "product-marketing.strategy.competitive_battlecard_system",
      },
      {
        id: "deck_modules",
        title: "Modular deck slides",
        type: "skill",
        skillId: "corporate-marketing.sales.sales_enablement_deck_system",
      },
      {
        id: "objections",
        title: "Objection one-pagers",
        type: "skill",
        skillId: "product-marketing.enablement.objection_handling_one_pagers",
      },
      {
        id: "gate",
        title: "Sales leadership review",
        type: "gate",
        gateCriteria: ["AE feedback incorporated", "PMM + sales aligned"],
      },
    ],
    outputChecklist: ["Battlecards", "Deck module pack", "3 objection one-pagers"],
    relatedWorkflows: ["product-marketing.tier1_launch"],
  },
  {
    id: "corporate-marketing.earnings_kit",
    title: "Quarterly earnings visual kit",
    vertical: "corporate-marketing",
    summary: "Results one-pager, social graphics, and investor email header for earnings week.",
    whenToUse: ["Public or private quarterly results announcement"],
    whenNotToUse: ["Ad-hoc product news"],
    estimatedMinutes: 90,
    primaryPlatforms: ["LinkedIn", "Investor email", "Press"],
    skillsUsed: [
      "corporate-marketing.content.design_earnings_visual_summary",
      "corporate-marketing.pr.press_release_visual_companion",
    ],
    docPath: "corporate-marketing/workflows/earnings-kit.md",
    steps: [
      {
        id: "metrics",
        title: "Key metrics lock",
        type: "input",
        inputs: [
          { key: "headline_metric", label: "Headline metric", required: true },
          { key: "supporting_stats", label: "3 supporting stats", required: true, multiline: true },
        ],
      },
      {
        id: "one_pager",
        title: "Visual one-pager",
        type: "skill",
        skillId: "corporate-marketing.content.design_earnings_visual_summary",
      },
      {
        id: "social",
        title: "Social graphics",
        type: "generate",
        jobType: "corporate_hero",
        promptTemplate: "Corporate earnings summary infographic style, data-forward, minimal, no faces",
      },
      {
        id: "press",
        title: "Press companion",
        type: "skill",
        skillId: "corporate-marketing.pr.press_release_visual_companion",
      },
      {
        id: "gate",
        title: "IR + legal approval",
        type: "gate",
        gateCriteria: ["IR approved numbers", "Legal cleared forward-looking statements"],
      },
    ],
    outputChecklist: ["One-pager PDF", "LinkedIn carousel", "Email header", "Press kit"],
    relatedWorkflows: [],
  },
];
