import type { WorkflowDefinition } from "../types";

export const EDITORIAL_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "editorial-marketing.pillar_page",
    title: "SEO pillar page production",
    vertical: "editorial-marketing",
    summary: "Keyword research → brief → long-form → visuals → publish with fact-check gate.",
    whenToUse: ["Building topic cluster hub", "Targeting high-intent keyword"],
    whenNotToUse: ["News reaction (use newsletter workflow)", "Thin programmatic pages"],
    estimatedMinutes: 240,
    primaryPlatforms: ["Blog", "Newsletter", "LinkedIn"],
    skillsUsed: [
      "editorial-marketing.seo.topic_cluster_and_pillar_page_plan",
      "editorial-marketing.seo.search_intent_content_brief",
      "editorial-marketing.ai.ai_fact_check_and_citation_gate",
    ],
    docPath: "editorial-marketing/workflows/pillar-page-production.md",
    steps: [
      {
        id: "keyword",
        title: "Target keyword",
        type: "input",
        inputs: [
          { key: "primary_keyword", label: "Primary keyword", required: true },
          { key: "search_intent", label: "Search intent", required: true },
          { key: "cluster_topics", label: "Spoke topics (5-10)", required: true, multiline: true },
        ],
      },
      {
        id: "cluster_plan",
        title: "Cluster architecture",
        type: "skill",
        skillId: "editorial-marketing.seo.topic_cluster_and_pillar_page_plan",
      },
      {
        id: "brief",
        title: "SERP-informed brief",
        type: "skill",
        skillId: "editorial-marketing.seo.search_intent_content_brief",
      },
      {
        id: "outline",
        title: "AI outline from research",
        type: "skill",
        skillId: "editorial-marketing.ai.ai_outline_from_keyword_research",
      },
      {
        id: "draft",
        title: "Long-form structure",
        type: "skill",
        skillId: "editorial-marketing.writing.long_form_article_structure",
      },
      {
        id: "hero",
        title: "Editorial hero",
        type: "generate",
        jobType: "editorial_hero",
        promptTemplate: "Editorial blog hero, typography-led, sophisticated, {{topic}} abstract",
      },
      {
        id: "fact_check",
        title: "Fact-check gate",
        type: "gate",
        skillId: "editorial-marketing.ai.ai_fact_check_and_citation_gate",
        gateCriteria: ["Every stat has source", "No unsourced claims", "Editor review"],
      },
      {
        id: "publish",
        title: "Publish checklist",
        type: "checklist",
        checklistItems: ["Internal links to spokes", "Meta title/desc", "Schema markup", "Newsletter teaser scheduled"],
      },
    ],
    outputChecklist: ["Pillar page live", "Cluster map updated", "5+ internal links planned"],
    relatedWorkflows: ["editorial-marketing.content_cluster", "editorial-marketing.article_social_ladder"],
  },
  {
    id: "editorial-marketing.content_cluster",
    title: "Content cluster sprint (4 weeks)",
    vertical: "editorial-marketing",
    summary: "Ship one hub + 4 spokes in 4 weeks with repurposing ladder.",
    whenToUse: ["SEO growth sprint", "New content pillar launch"],
    whenNotToUse: ["Single article only"],
    estimatedMinutes: 960,
    primaryPlatforms: ["Blog", "Social", "Newsletter"],
    skillsUsed: [
      "editorial-marketing.seo.topic_cluster_and_pillar_page_plan",
      "editorial-marketing.distribution.organic_social_teaser_ladder",
    ],
    docPath: "editorial-marketing/workflows/content-cluster-sprint.md",
    steps: [
      {
        id: "pillar",
        title: "Week 1: Pillar page",
        type: "skill",
        skillId: "editorial-marketing.seo.topic_cluster_and_pillar_page_plan",
        description: "Run pillar-page workflow or link existing hub.",
      },
      {
        id: "spoke1",
        title: "Week 2: Spoke 1",
        type: "input",
        inputs: [{ key: "spoke1_topic", label: "Spoke 1 topic", required: true }],
      },
      {
        id: "spoke2",
        title: "Week 3: Spoke 2 + 3",
        type: "input",
        inputs: [{ key: "spoke2_3", label: "Spoke 2 & 3 topics", required: true, multiline: true }],
      },
      {
        id: "spoke4",
        title: "Week 4: Spoke 4 + refresh",
        type: "skill",
        skillId: "editorial-marketing.ai.ai_refresh_decaying_content",
      },
      {
        id: "repurpose",
        title: "Social teaser ladder",
        type: "skill",
        skillId: "editorial-marketing.distribution.organic_social_teaser_ladder",
      },
    ],
    outputChecklist: ["1 pillar + 4 spokes live", "Social ladder per article"],
    relatedWorkflows: ["editorial-marketing.pillar_page"],
  },
  {
    id: "editorial-marketing.newsletter_edition",
    title: "Newsletter edition production",
    vertical: "editorial-marketing",
    summary: "Weekly or monthly editorial newsletter from template to send.",
    whenToUse: ["Recurring newsletter cadence"],
    whenNotToUse: ["One-off product email (use PMM)"],
    estimatedMinutes: 90,
    primaryPlatforms: ["Email", "Blog archive"],
    skillsUsed: ["editorial-marketing.writing.newsletter_edition_template"],
    docPath: "editorial-marketing/workflows/newsletter-edition.md",
    steps: [
      {
        id: "theme",
        title: "Edition theme",
        type: "input",
        inputs: [
          { key: "subject_line", label: "Subject line", required: true },
          { key: "sections", label: "Section outline", required: true, multiline: true },
        ],
      },
      {
        id: "template",
        title: "Apply template",
        type: "skill",
        skillId: "editorial-marketing.writing.newsletter_edition_template",
      },
      {
        id: "visual",
        title: "Header visual",
        type: "generate",
        jobType: "editorial_hero",
        promptTemplate: "Email newsletter header, editorial, minimal typography",
      },
      {
        id: "gate",
        title: "Editor approval",
        type: "gate",
        gateCriteria: ["Links tested", "Unsubscribe working", "Fact-check on claims"],
      },
    ],
    outputChecklist: ["Newsletter sent", "Web archive URL"],
    relatedWorkflows: ["editorial-marketing.article_social_ladder"],
  },
  {
    id: "editorial-marketing.article_social_ladder",
    title: "Article → social teaser ladder",
    vertical: "editorial-marketing",
    summary: "One article becomes thread, carousel, quote cards, and short video.",
    whenToUse: ["After publishing long-form content"],
    whenNotToUse: ["Before fact-check gate passed"],
    estimatedMinutes: 60,
    primaryPlatforms: ["LinkedIn", "X", "Instagram"],
    skillsUsed: ["editorial-marketing.distribution.organic_social_teaser_ladder"],
    docPath: "editorial-marketing/workflows/article-social-ladder.md",
    steps: [
      {
        id: "article",
        title: "Article URL",
        type: "input",
        inputs: [{ key: "article_url", label: "Published article URL", required: true }],
      },
      {
        id: "extract",
        title: "Extract hooks & quotes",
        type: "skill",
        skillId: "editorial-marketing.distribution.organic_social_teaser_ladder",
      },
      {
        id: "quote_cards",
        title: "Quote card graphics",
        type: "generate",
        jobType: "campaign_photo",
        promptTemplate: "Editorial quote card, typography-led, pull quote style",
      },
      {
        id: "thread",
        title: "Thread / carousel copy",
        type: "checklist",
        checklistItems: ["LinkedIn thread drafted", "IG carousel 5 slides", "Link in first comment"],
      },
    ],
    outputChecklist: ["3+ social assets", "7-day promo schedule"],
    relatedWorkflows: ["editorial-marketing.pillar_page"],
  },
];
