import type { WorkflowDefinition } from "../types";

export const FASHION_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "fashion-luxury.capsule_drop",
    title: "Capsule drop hype sequence",
    vertical: "fashion-luxury",
    summary: "Tease → drop → sellout narrative → archive. Full luxury drop workflow.",
    whenToUse: ["Limited capsule or collab drop", "Seasonal micro-collection"],
    whenNotToUse: ["Full season lookbook (use lookbook workflow)", "Evergreen catalog"],
    estimatedMinutes: 360,
    primaryPlatforms: ["Instagram", "TikTok", "Email", "Ecommerce"],
    skillsUsed: [
      "fashion-luxury.campaign.capsule_drop_hype_sequence",
      "fashion-luxury.ai.ai_look_generation_moodboard",
      "fashion-luxury.social.instagram_reels_fashion_native",
    ],
    docPath: "fashion-luxury/workflows/capsule-drop.md",
    steps: [
      {
        id: "concept",
        title: "Drop concept",
        type: "input",
        inputs: [
          { key: "drop_name", label: "Drop name", required: true },
          { key: "drop_date", label: "Drop date & time", required: true },
          { key: "units", label: "Unit count (scarcity)", required: true },
          { key: "concept", label: "Creative concept", required: true, multiline: true },
        ],
      },
      {
        id: "luxury_codes",
        title: "Luxury brand codes check",
        type: "skill",
        skillId: "fashion-luxury.strategy.define_luxury_brand_codes",
      },
      {
        id: "moodboard",
        title: "AI moodboard (refs only)",
        type: "generate",
        jobType: "fashion_moodboard",
        promptTemplate: "Luxury fashion moodboard, {{concept}}, editorial lighting, film grain, no logos",
        description: "AI for mood only — hero assets from human shoot.",
      },
      {
        id: "tease",
        title: "Tease phase (T-7 to T-1)",
        type: "skill",
        skillId: "fashion-luxury.campaign.capsule_drop_hype_sequence",
      },
      {
        id: "reels",
        title: "Reels / TikTok motion",
        type: "generate",
        jobType: "image_to_video_social",
        promptTemplate: "Luxury fashion motion teaser, slow reveal, cinematic",
      },
      {
        id: "email",
        title: "VIP early access email",
        type: "checklist",
        checklistItems: ["VIP segment defined", "Early access link tested", "Sold-out waitlist ready"],
      },
      {
        id: "drop",
        title: "Drop day",
        type: "checklist",
        checklistItems: [
          "PDP live",
          "IG/TikTok posted at drop time",
          "Inventory sync verified",
          "Archive plan for sold-out state",
        ],
      },
      {
        id: "gate",
        title: "Creative director sign-off",
        type: "gate",
        gateCriteria: [
          "Hero imagery from human shoot",
          "Model releases on file",
          "AI policy compliant",
        ],
        skillId: "fashion-luxury.ai.ai_on_model_vs_ghost_mannequin_policy",
      },
    ],
    outputChecklist: ["Tease assets", "Drop day assets", "Email flows", "Post-drop archive"],
    relatedWorkflows: ["fashion-luxury.lookbook_season", "fashion-luxury.collab_announce"],
  },
  {
    id: "fashion-luxury.lookbook_season",
    title: "Season lookbook production",
    vertical: "fashion-luxury",
    summary: "Season narrative → art direction → lookbook → retail bridge.",
    whenToUse: ["SS/FW season launch", "Campaign reset"],
    whenNotToUse: ["Single drop only"],
    estimatedMinutes: 720,
    primaryPlatforms: ["Lookbook PDF", "Instagram", "Journal", "Retail"],
    skillsUsed: [
      "fashion-luxury.strategy.season_narrative_concept",
      "fashion-luxury.campaign.lookbook_art_direction_brief",
      "fashion-luxury.editorial.fashion_editorial_layout_system",
    ],
    docPath: "fashion-luxury/workflows/lookbook-season.md",
    steps: [
      {
        id: "narrative",
        title: "Season narrative",
        type: "skill",
        skillId: "fashion-luxury.strategy.season_narrative_concept",
      },
      {
        id: "art_direction",
        title: "Art direction brief",
        type: "skill",
        skillId: "fashion-luxury.campaign.lookbook_art_direction_brief",
      },
      {
        id: "moodboard",
        title: "Moodboard generation",
        type: "generate",
        jobType: "fashion_moodboard",
        promptTemplate: "{{season}} luxury lookbook mood, {{narrative}}, high fashion editorial",
      },
      {
        id: "layout",
        title: "Editorial layout system",
        type: "skill",
        skillId: "fashion-luxury.editorial.fashion_editorial_layout_system",
      },
      {
        id: "runway_retail",
        title: "Runway to retail bridge",
        type: "skill",
        skillId: "fashion-luxury.campaign.runway_to_retail_campaign_bridge",
      },
      {
        id: "pdp",
        title: "Premium PDP templates",
        type: "skill",
        skillId: "fashion-luxury.editorial.ecommerce_pdp_premium_template",
      },
      {
        id: "gate",
        title: "Creative + legal",
        type: "gate",
        gateCriteria: ["Shoot assets ingested", "Model releases", "Retouch standards met"],
      },
    ],
    outputChecklist: ["Lookbook PDF", "Journal feature", "Retail VM guide", "PDP templates"],
    relatedWorkflows: ["fashion-luxury.capsule_drop"],
  },
  {
    id: "fashion-luxury.collab_announce",
    title: "Collaboration announcement",
    vertical: "fashion-luxury",
    summary: "Co-brand announcement for luxury × luxury or luxury × street collabs.",
    whenToUse: ["Confirmed collaboration", "Dual-brand legal cleared"],
    whenNotToUse: ["Rumor phase"],
    estimatedMinutes: 180,
    primaryPlatforms: ["Instagram", "Press", "Email"],
    skillsUsed: ["fashion-luxury.campaign.collaboration_co_brand_announcement"],
    docPath: "fashion-luxury/workflows/collab-announcement.md",
    steps: [
      {
        id: "partners",
        title: "Partner details",
        type: "input",
        inputs: [
          { key: "brand_a", label: "Brand A", required: true },
          { key: "brand_b", label: "Brand B", required: true },
          { key: "announce_date", label: "Announce date", required: true },
        ],
      },
      {
        id: "co_brand_rules",
        title: "Co-brand lockup rules",
        type: "skill",
        skillId: "fashion-luxury.campaign.collaboration_co_brand_announcement",
      },
      {
        id: "hero",
        title: "Announcement hero",
        type: "generate",
        jobType: "fashion_moodboard",
        promptTemplate: "Luxury fashion collaboration teaser, dual brand energy, no visible logos",
      },
      {
        id: "gate",
        title: "Both brands approve",
        type: "gate",
        gateCriteria: ["Dual brand sign-off", "Legal co-brand agreement"],
      },
    ],
    outputChecklist: ["Hero asset", "Press release", "Social cutdowns"],
    relatedWorkflows: ["fashion-luxury.capsule_drop"],
  },
];
