import type { WorkflowDefinition } from "../types";

export const MARKETING_STACK_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "marketing-stack.campaign_orchestration",
    title: "End-to-end campaign orchestration",
    vertical: "marketing-stack",
    summary:
      "Brief → platform pick → AI tool pick → create → QA → publish. The master workflow for any campaign.",
    whenToUse: [
      "Starting any new campaign and you need the full path",
      "Onboarding a new client or vertical",
      "You feel overwhelmed by tool choice",
    ],
    whenNotToUse: [
      "Single asset tweak (use Media Studio directly)",
      "Vertical-specific launch already has a dedicated workflow",
    ],
    estimatedMinutes: 45,
    primaryPlatforms: ["Varies by objective"],
    skillsUsed: [
      "marketing-stack.platform.select_platform_for_objective",
      "marketing-stack.ai.route_tool_for_job",
      "marketing-stack.workflow.ai_human_qa_gates",
      "platform.brand_studio.run_qa_pipeline",
    ],
    docPath: "marketing-stack/workflows/campaign-orchestration.md",
    steps: [
      {
        id: "brief",
        title: "Campaign brief",
        description: "Capture objective, audience, timeline, and success metric in one place.",
        type: "input",
        inputs: [
          { key: "objective", label: "Campaign objective", required: true, multiline: true },
          { key: "audience", label: "Primary audience", required: true },
          { key: "deadline", label: "Publish deadline", required: true },
          { key: "success_metric", label: "How we measure success", required: true },
        ],
      },
      {
        id: "tokens",
        title: "Load brand tokens",
        description: "Attach client token JSON and verify logo matrix exists.",
        type: "skill",
        skillId: "brand-system.tokens.define_design_tokens",
      },
      {
        id: "platform",
        title: "Select platform",
        description: "Pick primary channel — do not co-primary two channels.",
        type: "route",
        routeObjective: "b2b_pipeline",
        skillId: "marketing-stack.platform.select_platform_for_objective",
      },
      {
        id: "ai_tool",
        title: "Route AI tools",
        description: "Map each asset job to the right generator — no manual tool shopping.",
        type: "skill",
        skillId: "marketing-stack.ai.route_tool_for_job",
      },
      {
        id: "produce",
        title: "Produce assets",
        description: "Generate visuals via Media Studio using routed models.",
        type: "generate",
        jobType: "campaign_photo",
        promptTemplate: "{{campaign_name}} — {{visual_direction}} — on-brand, professional",
      },
      {
        id: "qa",
        title: "QA gates",
        description: "Token lint + vertical-specific human gates before publish.",
        type: "gate",
        skillId: "marketing-stack.workflow.ai_human_qa_gates",
        gateCriteria: [
          "Token lint passed",
          "No uncanny AI faces in hero (corporate/luxury)",
          "Copy claims have citations (editorial)",
          "Approver signed off",
        ],
      },
      {
        id: "publish",
        title: "Publish & archive",
        description: "Schedule to primary platform and archive deliverable bundle.",
        type: "checklist",
        checklistItems: [
          "Scheduled on primary platform",
          "UTM / tracking links set",
          "DAM folder created",
          "Deliverable manifest exported",
        ],
      },
    ],
    outputChecklist: [
      "Campaign brief saved",
      "Platform decision documented",
      "Assets generated and QA-approved",
      "Published or scheduled",
      "Archive bundle in DAM",
    ],
    relatedWorkflows: [
      "corporate-marketing.thought_leadership",
      "product-marketing.tier1_launch",
      "fashion-luxury.capsule_drop",
    ],
  },
  {
    id: "marketing-stack.qa_pipeline",
    title: "AI + human QA pipeline",
    vertical: "marketing-stack",
    summary: "Mandatory checkpoints before any asset goes live — by asset type.",
    whenToUse: ["Before publishing any AI-assisted asset", "Setting up approval chain for a client"],
    whenNotToUse: ["Internal draft-only exploration"],
    estimatedMinutes: 15,
    primaryPlatforms: ["All"],
    skillsUsed: [
      "marketing-stack.workflow.ai_human_qa_gates",
      "brand-system.qa.run_token_lint_on_asset",
      "platform.brand_studio.approval_workflow_state",
    ],
    docPath: "marketing-stack/workflows/qa-pipeline.md",
    steps: [
      {
        id: "classify",
        title: "Classify asset type",
        description: "Hero image, copy, video, logo, or editorial — each has different gates.",
        type: "input",
        inputs: [
          { key: "asset_type", label: "Asset type", required: true },
          { key: "vertical", label: "Vertical pack", required: true },
        ],
      },
      {
        id: "lint",
        title: "Token lint",
        description: "Run brand-system lint on colors, type, logo usage.",
        type: "skill",
        skillId: "brand-system.qa.run_token_lint_on_asset",
      },
      {
        id: "vertical_gate",
        title: "Vertical QA gate",
        description: "Fashion: no AI on-model hero. Editorial: citation check. Corporate: exec voice.",
        type: "gate",
        gateCriteria: [
          "Vertical-specific rules passed",
          "Legal/compliance if required",
        ],
      },
      {
        id: "approve",
        title: "Approval state",
        description: "Move asset draft → review → approved.",
        type: "skill",
        skillId: "platform.brand_studio.approval_workflow_state",
      },
    ],
    outputChecklist: ["Asset approved and ready to publish"],
    relatedWorkflows: ["marketing-stack.campaign_orchestration"],
  },
];
