import type { WorkflowDefinition } from "../types";

export const PERSONAL_OS_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "personal-os.weekly_alignment",
    title: "Weekly personal alignment",
    vertical: "personal-os",
    summary:
      "Sunday night, 15 minutes: alignment brief + scorecard + next week top 3. Your home rhythm.",
    whenToUse: [
      "Every Sunday night (~15 min)",
      "Feeling scattered or reactivity-driven",
    ],
    whenNotToUse: ["Mid-crisis — stabilize first, align after"],
    estimatedMinutes: 15,
    primaryPlatforms: ["Personal OS", "Notes app"],
    skillsUsed: [
      "personal-os.doc.write_weekly_alignment_brief",
      "personal-os.doc.write_personal_scorecard",
      "personal-os.doc.write_personal_status_report",
    ],
    docPath: "personal-os/workflows/weekly-alignment.md",
    steps: [
      {
        id: "energy",
        title: "Honest energy check",
        description: "Low / medium / high — plan capacity, not fantasy.",
        type: "input",
        inputs: [
          { key: "energy", label: "Energy this week (low/med/high)", required: true },
          { key: "what_drained", label: "What drained you?", required: false, multiline: true },
        ],
      },
      {
        id: "scorecard",
        title: "Personal scorecard",
        description: "5 lead + 5 lag — numbers or honest ranges, not guilt.",
        type: "skill",
        skillId: "personal-os.doc.write_personal_scorecard",
      },
      {
        id: "alignment",
        title: "Weekly alignment brief",
        description: "One intention, top 3 outcomes, constraints (time, money, people).",
        type: "skill",
        skillId: "personal-os.doc.write_weekly_alignment_brief",
      },
      {
        id: "top3",
        title: "Lock top 3",
        type: "input",
        inputs: [
          { key: "top_1", label: "Top priority 1", required: true },
          { key: "top_2", label: "Top priority 2", required: true },
          { key: "top_3", label: "Top priority 3", required: false },
        ],
      },
      {
        id: "sops",
        title: "Non-negotiable SOPs check",
        type: "checklist",
        checklistItems: [
          "Meds / health anchor scheduled",
          "Money touchpoint day set",
          "Sleep window protected",
          "One social/connect touch planned",
        ],
      },
    ],
    outputChecklist: ["Alignment brief saved", "Scorecard updated", "Top 3 visible somewhere you'll see daily"],
    relatedWorkflows: ["personal-os.personal_aar", "personal-os.life_project_charter"],
  },
  {
    id: "personal-os.life_project_charter",
    title: "Life project charter",
    vertical: "personal-os",
    summary:
      "Before big personal commitments: scope, out-of-scope, success criteria, risks. Same brain you used for big days — for your life.",
    whenToUse: [
      "≥4 hours/week for 2+ weeks",
      "≥$500 or high emotional load",
      "Move, launch, health protocol, major relationship conversation prep",
    ],
    whenNotToUse: ["Small errands", "Already in weekly top 3"],
    estimatedMinutes: 45,
    primaryPlatforms: ["Personal OS"],
    skillsUsed: [
      "personal-os.doc.write_life_project_charter",
      "personal-os.doc.write_personal_risk_register",
      "personal-os.doc.write_concept_note_personal",
    ],
    docPath: "personal-os/workflows/life-project-charter.md",
    steps: [
      {
        id: "concept",
        title: "Concept note (if idea is fuzzy)",
        type: "skill",
        skillId: "personal-os.doc.write_concept_note_personal",
        optional: true,
      },
      {
        id: "charter",
        title: "Life project charter",
        type: "input",
        inputs: [
          { key: "project_name", label: "Project name", required: true },
          { key: "why_now", label: "Why now?", required: true, multiline: true },
          { key: "success", label: "Done looks like…", required: true, multiline: true },
          { key: "not_doing", label: "Explicitly NOT doing", required: true, multiline: true },
          { key: "deadline", label: "Target date", required: false },
        ],
      },
      {
        id: "risk",
        title: "Personal risk register",
        description: "Hyperfocus trap, isolation, overspend, health neglect — mitigation per risk.",
        type: "skill",
        skillId: "personal-os.doc.write_personal_risk_register",
      },
      {
        id: "gate",
        title: "Future You sign-off",
        description: "Would calm-you on a good day approve this scope?",
        type: "gate",
        gateCriteria: ["Scope fits actual capacity", "Out-of-scope written", "First next action < 30 min"],
      },
    ],
    outputChecklist: ["Charter saved", "Risks named", "First action scheduled"],
    relatedWorkflows: ["personal-os.weekly_alignment", "personal-os.personal_aar"],
  },
  {
    id: "personal-os.personal_aar",
    title: "Personal after action review",
    vertical: "personal-os",
    summary: "Blameless 20-min review after hard weeks or finished projects — feeds next alignment.",
    whenToUse: ["After launch week", "After travel", "After emotional intensity", "End of life project"],
    whenNotToUse: ["Daily — use weekly alignment instead"],
    estimatedMinutes: 20,
    primaryPlatforms: ["Personal OS"],
    skillsUsed: [
      "personal-os.doc.write_personal_aar",
      "personal-os.doc.write_personal_decision_memo",
    ],
    docPath: "personal-os/workflows/personal-aar.md",
    steps: [
      {
        id: "context",
        title: "What period / project?",
        type: "input",
        inputs: [
          { key: "period", label: "Week of or project name", required: true },
          { key: "charter_link", label: "Charter link (if any)", required: false },
        ],
      },
      {
        id: "aar",
        title: "Write AAR",
        description: "Worked / didn't / keep / stop / start.",
        type: "skill",
        skillId: "personal-os.doc.write_personal_aar",
      },
      {
        id: "decisions",
        title: "Decision memos",
        description: "Any 'never again' or 'always do' → decision memo, not vibes.",
        type: "skill",
        skillId: "personal-os.doc.write_personal_decision_memo",
        optional: true,
      },
      {
        id: "next",
        title: "Feed weekly alignment",
        type: "checklist",
        checklistItems: ["One improvement with owner (you) and date", "Scorecard metric to watch", "Schedule next weekly alignment"],
      },
    ],
    outputChecklist: ["AAR saved", "Decisions recorded", "Next alignment scheduled"],
    relatedWorkflows: ["personal-os.weekly_alignment"],
  },
  {
    id: "personal-os.personal_creative_brief",
    title: "Personal creative brief",
    vertical: "personal-os",
    summary: "Before side projects or content batches — align like you would at work, then produce.",
    whenToUse: ["New creative project", "Content batch", "Building in Brand Studio / quiver-clone"],
    whenNotToUse: ["Pure play with no deliverable — skip brief, enjoy"],
    estimatedMinutes: 20,
    primaryPlatforms: ["Personal brand", "Studio"],
    skillsUsed: [
      "personal-os.doc.write_personal_creative_brief",
      "personal-brand.strategy.define_personal_brand_positioning",
    ],
    docPath: "personal-os/workflows/personal-creative-brief.md",
    steps: [
      {
        id: "brief",
        title: "Personal creative brief",
        type: "input",
        inputs: [
          { key: "project", label: "What are you making?", required: true },
          { key: "audience", label: "For whom (even if future you)?", required: true },
          { key: "done", label: "Done definition", required: true, multiline: true },
          { key: "constraints", label: "Time / energy / money constraints", required: true, multiline: true },
        ],
      },
      {
        id: "brand_check",
        title: "Personal brand alignment",
        type: "skill",
        skillId: "personal-brand.strategy.define_personal_brand_positioning",
        optional: true,
      },
      {
        id: "route",
        title: "Route to production",
        type: "checklist",
        checklistItems: [
          "Public brand → personal-brand.thirty_day or creator.weekly_production",
          "Visuals → /app/studio",
          "Full campaign → marketing-stack.campaign_orchestration",
        ],
      },
    ],
    outputChecklist: ["Brief saved", "Production workflow chosen"],
    relatedWorkflows: ["personal-brand.thirty_day", "creator.weekly_production"],
  },
];
