import type { WorkflowDefinition } from "../types";

export const PMM_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: "product-marketing.tier1_launch",
    title: "Tier 1 product launch (GTM)",
    vertical: "product-marketing",
    summary: "Full launch: positioning, narrative, sales kit, web, email, demo video, analyst kit.",
    whenToUse: ["New product or major version", "Company priority launch"],
    whenNotToUse: ["Minor feature — use tier 2", "Internal-only release"],
    estimatedMinutes: 480,
    primaryPlatforms: ["Web", "Product Hunt", "Email", "Sales"],
    skillsUsed: [
      "product-marketing.launch.gtm_launch_tier_selection",
      "product-marketing.strategy.write_positioning_and_messaging_doc",
      "product-marketing.launch.launch_narrative_and_hook",
      "product-marketing.launch.sales_launch_kit",
    ],
    docPath: "product-marketing/workflows/tier1-launch.md",
    steps: [
      {
        id: "tier_confirm",
        title: "Confirm Tier 1 scope",
        type: "skill",
        skillId: "product-marketing.launch.gtm_launch_tier_selection",
        description: "Tier 1 = positioning + full asset suite + analyst/press.",
      },
      {
        id: "prd_intake",
        title: "PRD intake",
        type: "input",
        inputs: [
          { key: "product_name", label: "Product name", required: true },
          { key: "launch_date", label: "Launch date", required: true },
          { key: "prd_summary", label: "PRD summary", required: true, multiline: true },
          { key: "differentiation", label: "Key differentiation", required: true, multiline: true },
        ],
      },
      {
        id: "positioning",
        title: "Positioning & messaging doc",
        type: "skill",
        skillId: "product-marketing.strategy.write_positioning_and_messaging_doc",
      },
      {
        id: "ai_draft",
        title: "AI draft from PRD",
        type: "skill",
        skillId: "product-marketing.ai.ai_generate_pmm_draft_from_prd",
        description: "Human edit gate required — never publish raw AI copy.",
      },
      {
        id: "narrative",
        title: "Launch narrative & hook",
        type: "skill",
        skillId: "product-marketing.launch.launch_narrative_and_hook",
      },
      {
        id: "platform",
        title: "Launch channels",
        type: "route",
        routeObjective: "product_launch",
      },
      {
        id: "hero_visual",
        title: "Launch hero visual",
        type: "generate",
        jobType: "product_photo",
        promptTemplate: "{{product_name}} product launch hero, clean product marketing, on-brand",
      },
      {
        id: "demo_storyboard",
        title: "Demo storyboard",
        type: "skill",
        skillId: "product-marketing.content.product_demo_storyboard",
      },
      {
        id: "sales_kit",
        title: "Sales launch kit",
        type: "skill",
        skillId: "product-marketing.launch.sales_launch_kit",
      },
      {
        id: "email_sequence",
        title: "Customer email sequence",
        type: "skill",
        skillId: "product-marketing.launch.customer_announcement_email_sequence",
      },
      {
        id: "analyst",
        title: "Analyst & press kit",
        type: "skill",
        skillId: "product-marketing.launch.analyst_and_press_briefing_kit",
        optional: true,
      },
      {
        id: "gate",
        title: "Launch readiness review",
        type: "gate",
        gateCriteria: [
          "PMM + product + sales sign-off",
          "No synthetic testimonials",
          "Demo tested",
          "Tracking live",
        ],
      },
    ],
    outputChecklist: [
      "Positioning doc",
      "Landing page live",
      "Sales kit",
      "Email sequence scheduled",
      "Launch metrics dashboard",
    ],
    relatedWorkflows: ["product-marketing.tier2_launch", "product-marketing.positioning_from_prd"],
  },
  {
    id: "product-marketing.tier2_launch",
    title: "Tier 2 feature launch",
    vertical: "product-marketing",
    summary: "Lighter launch: changelog → blog → email → in-app — no full analyst kit.",
    whenToUse: ["Significant feature", "Existing product expansion"],
    whenNotToUse: ["Tier 1 new product", "Patch notes only"],
    estimatedMinutes: 120,
    primaryPlatforms: ["Blog", "Email", "In-app"],
    skillsUsed: [
      "product-marketing.launch.gtm_launch_tier_selection",
      "product-marketing.content.changelog_to_marketing_repurpose",
      "product-marketing.content.feature_adoption_campaign",
    ],
    docPath: "product-marketing/workflows/tier2-launch.md",
    steps: [
      {
        id: "scope",
        title: "Tier 2 scope",
        type: "skill",
        skillId: "product-marketing.launch.gtm_launch_tier_selection",
      },
      {
        id: "changelog",
        title: "Changelog intake",
        type: "input",
        inputs: [
          { key: "feature_name", label: "Feature name", required: true },
          { key: "changelog", label: "Changelog text", required: true, multiline: true },
          { key: "user_benefit", label: "User benefit (one line)", required: true },
        ],
      },
      {
        id: "repurpose",
        title: "Changelog → marketing",
        type: "skill",
        skillId: "product-marketing.content.changelog_to_marketing_repurpose",
      },
      {
        id: "visual",
        title: "Feature graphic",
        type: "generate",
        jobType: "product_photo",
        promptTemplate: "SaaS feature announcement graphic, UI mockup style, clean",
      },
      {
        id: "adoption",
        title: "Adoption campaign",
        type: "skill",
        skillId: "product-marketing.content.feature_adoption_campaign",
      },
      {
        id: "gate",
        title: "PM review",
        type: "gate",
        gateCriteria: ["Product verified accuracy", "Support briefed"],
      },
    ],
    outputChecklist: ["Blog post", "Email", "In-app announcement", "Help docs link"],
    relatedWorkflows: ["product-marketing.tier1_launch"],
  },
  {
    id: "product-marketing.positioning_from_prd",
    title: "Positioning from PRD",
    vertical: "product-marketing",
    summary: "PRD → positioning doc → messaging pillars in one working session.",
    whenToUse: ["Pre-launch positioning workshop", "Repositioning after win/loss"],
    whenNotToUse: ["Launch assets due tomorrow — use tier workflow"],
    estimatedMinutes: 90,
    primaryPlatforms: ["Internal"],
    skillsUsed: [
      "product-marketing.ai.ai_generate_pmm_draft_from_prd",
      "product-marketing.strategy.write_positioning_and_messaging_doc",
      "product-marketing.strategy.build_buyer_persona_research_synthesis",
    ],
    docPath: "product-marketing/workflows/positioning-from-prd.md",
    steps: [
      {
        id: "prd",
        title: "PRD upload",
        type: "input",
        inputs: [{ key: "prd", label: "PRD or spec", required: true, multiline: true }],
      },
      {
        id: "personas",
        title: "Buyer personas",
        type: "skill",
        skillId: "product-marketing.strategy.build_buyer_persona_research_synthesis",
      },
      {
        id: "ai_draft",
        title: "AI positioning draft",
        type: "skill",
        skillId: "product-marketing.ai.ai_generate_pmm_draft_from_prd",
      },
      {
        id: "workshop",
        title: "Human positioning workshop",
        type: "gate",
        gateCriteria: ["Category defined", "3 pillars locked", "Proof points assigned"],
      },
      {
        id: "doc",
        title: "Final positioning doc",
        type: "skill",
        skillId: "product-marketing.strategy.write_positioning_and_messaging_doc",
      },
    ],
    outputChecklist: ["Positioning & messaging doc v1"],
    relatedWorkflows: ["product-marketing.tier1_launch"],
  },
];
